openshift:
  image: llparse/openshift-origin:v0.0.1
  command: /usr/sbin/init
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.dns: 'true'
    io.rancher.scheduler.affinity:host_label: io.rancher.host.docker_version=1.10
    io.rancher.container.pull_image: always
  net: host
  privileged: true
  ports:
  - 31381:31381
  - 33518:33518
  environment:
    container: docker
  volumes:
  - /var/run/dbus:/var/run/dbus
  - /sys/fs/cgroup:/sys/fs/cgroup
#  - /var/run/docker.sock:/var/run/docker.sock
#  - /var/lib/docker:/var/lib/docker

orchestrator:
  image: llparse/ansible-runner:v0.0.1
  command: /run.sh
  labels:
    io.rancher.container.dns: 'true'
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: io.rancher.host.docker_version=1.10
    io.rancher.container.pull_image: always
  net: host
  links:
  - openshift
