.catalog:
  version: 0.0.1
etcd:
    retain_ip: true
    scale_policy:
        increment: 1
        max: 3
        min: 1
    metadata:
        scale_policy:
            min: 1
    health_check:
        port: 2378
        request_line: GET /health HTTP/1.0
        interval: 5000
        response_timeout: 3000
        unhealthy_threshold: 3
        healthy_threshold: 2
        recreate_on_quorum_strategy_config:
            quorum: 2
        strategy: recreateOnQuorum
