etcd:
  image: llparse/etcd:v2.3.7-7
  labels:
    io.rancher.scheduler.affinity:host_label: etcd=true
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: backup
  environment:
    RANCHER_DEBUG: '${RANCHER_DEBUG}'
    EMBEDDED_BACKUPS: 'false'
  volumes:
  - etcd:/pdata

backup:
  image: llparse/etcd:v2.3.7-7
  command: rolling_backup
  environment:
    BACKUP_PERIOD: 15m
    BACKUP_RETENTION: 1h
    RANCHER_DEBUG: '${RANCHER_DEBUG}'
  net: container:etcd
  volumes:
  - /var/etcd/backups:/data-backup
  volumes_from:
  - etcd

openvswitch:
  image: openshift/openvswitch:v1.2.1
  privileged: true
  net: host
  pid: host
  labels:
    io.rancher.scheduler.global: 'true'
  volumes:
  - /lib/modules:/lib/modules
  - /run:/run
  - /sys:/sys:ro
  - /etc/origin/openvswitch:/etc/openvswitch

master:
  image: llparse/origin:v1.2.1
  command: bootstrap_master
  labels:
    io.rancher.container.agent.role: environment
    io.rancher.container.create_agent: 'true'
    io.rancher.container.dns: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: master=true
  environment:
    RANCHER_DEBUG: '${RANCHER_DEBUG}'
    KUBECONFIG: /etc/origin/master/admin.kubeconfig
    CREATE_EXAMPLES: '${CREATE_EXAMPLES}'
    CREATE_ROUTER: '${CREATE_ROUTER}'
    CREATE_REGISTRY: '${CREATE_REGISTRY}'
  expose:
  - 8443:8443/tcp
  links:
  - etcd
  net: host
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /etc/docker/certs.d:/etc/docker/certs.d
  - /etc/origin/master:/etc/origin/master

node:
  image: llparse/origin:v1.2.1
  command: bootstrap_node
  labels:
    io.rancher.container.agent.role: environment
    io.rancher.container.create_agent: 'true'
    io.rancher.container.dns: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label_ne: nopods=true
    io.rancher.scheduler.global: 'true'
  environment:
    RANCHER_DEBUG: '${RANCHER_DEBUG}'
    KUBECONFIG: /etc/origin/master/admin.kubeconfig
  expose:
  - 10250:10250/tcp
  links:
  - master
  - openvswitch
  net: host
  pid: host
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  # necessary for configuring secure docker registry
  - /etc/docker/certs.d:/etc/docker/certs.d
  # volumes only seem to work with a host bind-mount
  - /openshift.local.volumes:/openshift.local.volumes
  - /:/rootfs:ro
  - /dev:/dev
  - /lib/modules:/lib/modules
  - /run:/run
  - /sys:/sys:ro
  - /usr/bin/docker:/usr/bin/docker:ro
  - /var/lib/docker:/var/lib/docker
  - /var/lib/origin:/var/lib/origin
  - /var/log:/var/log
  - /etc/localtime:/etc/localtime:ro
  # persist config to host
  - /etc/origin/node:/etc/origin/node
  - /etc/origin/openvswitch:/etc/openvswitch
  #- /etc/origin/sdn:/etc/openshift-sdn
